// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMn13AU1X1vuom55DA-JFxZpX1cF8CFQ',
    appId: '1:173273587991:web:b67b8669084991e493d752',
    messagingSenderId: '173273587991',
    projectId: 'yugen-1f240',
    authDomain: 'yugen-1f240.firebaseapp.com',
    storageBucket: 'yugen-1f240.firebasestorage.app',
    measurementId: 'G-8W6P5156X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIkVLa0pilQTMBwy5bUNt9WLQsJhNz4-o',
    appId: '1:173273587991:android:9bb48c27374bccb993d752',
    messagingSenderId: '173273587991',
    projectId: 'yugen-1f240',
    storageBucket: 'yugen-1f240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTLgF2McI41wbFcnHLzsbP-9dzlO5cE0o',
    appId: '1:173273587991:ios:e1e50c1a8849796c93d752',
    messagingSenderId: '173273587991',
    projectId: 'yugen-1f240',
    storageBucket: 'yugen-1f240.firebasestorage.app',
    iosBundleId: 'com.example.flutterPrograms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTLgF2McI41wbFcnHLzsbP-9dzlO5cE0o',
    appId: '1:173273587991:ios:e1e50c1a8849796c93d752',
    messagingSenderId: '173273587991',
    projectId: 'yugen-1f240',
    storageBucket: 'yugen-1f240.firebasestorage.app',
    iosBundleId: 'com.example.flutterPrograms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbMn13AU1X1vuom55DA-JFxZpX1cF8CFQ',
    appId: '1:173273587991:web:2ebff51a7d3ac60293d752',
    messagingSenderId: '173273587991',
    projectId: 'yugen-1f240',
    authDomain: 'yugen-1f240.firebaseapp.com',
    storageBucket: 'yugen-1f240.firebasestorage.app',
    measurementId: 'G-10VXYXY9GW',
  );
}
